# Generated by Django 4.2.9 on 2024-01-29 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0013_historicaluser_historicalgroup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUser',
        ),
    ]
