# Generated by Django 4.2.9 on 2025-03-05 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0014_delete_historicaluser'),
    ]

    operations = [
    ]
