# Generated by Django 4.2.7 on 2024-01-23 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('i', 'Professor/Primary Investigator'), ('p', 'Postdoctoral Fellow'), ('c', 'Collaborator'), ('g', 'Graduate Student'), ('t', 'Technician'), ('u', 'Undergraduate'), ('o', 'Other/Undefined')], default='o', max_length=1)),
                ('initials', models.CharField(max_length=4, unique=True)),
                ('other_associated_initials', models.CharField(blank=True, max_length=100, null=True)),
                ('active_status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StrainRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain_numbers_start', models.IntegerField(default=-1)),
                ('strain_numbers_end', models.IntegerField(default=-1)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strain_ranges', to='profiles.userprofile')),
            ],
        ),
    ]
