# Generated by Django 4.2.7 on 2024-01-23 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('o', 'Other/Undefined'), ('i', 'Professor/Primary Investigator'), ('p', 'Postdoctoral Fellow'), ('c', 'Collaborator'), ('g', 'Graduate Student'), ('t', 'Technician'), ('u', 'Undergraduate')], default='o', max_length=1),
        ),
    ]
