# Generated by Django 4.2.7 on 2023-11-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='initials',
            field=models.CharField(max_length=4, unique=True),
        ),
    ]
