# Generated by Django 4.2.7 on 2024-01-22 01:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='strain_numbers_end',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='strain_numbers_start',
        ),
        migrations.CreateModel(
            name='StrainRange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strain_numbers_start', models.IntegerField(default=-1)),
                ('strain_numbers_end', models.IntegerField(default=-1)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strain_ranges', to='profiles.userprofile')),
            ],
        ),
    ]
