# Generated by Django 4.2.7 on 2024-01-22 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_userprofile_strain_numbers_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='other_associated_initials',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
