# Generated by Django 4.2.9 on 2024-01-28 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_alter_historicaluserprofile_initials_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='all_associated_initials',
        ),
        migrations.AddField(
            model_name='userinitials',
            name='user_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='all_associated_initials', to='profiles.userprofile'),
        ),
    ]
