# Generated by Django 4.2.7 on 2023-12-22 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='active_status',
            field=models.BooleanField(default=False),
        ),
    ]
