# Generated by Django 4.2.7 on 2024-01-11 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_historicaluserprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalUserProfile',
        ),
    ]
