# Generated by Django 4.2.7 on 2023-11-22 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dewar', models.IntegerField()),
                ('rack', models.IntegerField()),
                ('box', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FreezeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_frozen', models.DateField(null=True)),
                ('freezer_initials', models.CharField(default='N/A', max_length=15)),
                ('started_test', models.BooleanField(default=False)),
                ('completed_test', models.BooleanField(default=False)),
                ('passed_test', models.BooleanField(default=False)),
                ('tester_initials', models.CharField(max_length=15, null=True)),
                ('tester_comments', models.CharField(max_length=255, null=True)),
                ('test_check_date', models.DateField(null=True)),
                ('stored', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wja', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_color', models.CharField(default='N/A', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_thawed', models.DateField(null=True)),
                ('thawed', models.BooleanField(default=False)),
                ('thaw_requester', models.CharField(max_length=50, null=True)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tube_set', to='ArribereNemaStocks.box')),
                ('freeze_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tube_set', to='ArribereNemaStocks.freezegroup')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tube_set', to='ArribereNemaStocks.strain')),
            ],
        ),
        migrations.AddField(
            model_name='freezegroup',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArribereNemaStocks.strain'),
        ),
    ]
