# Generated by Django 4.2.7 on 2024-01-19 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dewar', models.IntegerField()),
                ('rack', models.IntegerField()),
                ('box', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FreezeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_stored', models.DateField(null=True)),
                ('started_test', models.BooleanField(default=False)),
                ('completed_test', models.BooleanField(default=False)),
                ('passed_test', models.BooleanField(default=False)),
                ('tester_comments', models.CharField(max_length=255, null=True)),
                ('test_check_date', models.DateField(null=True)),
                ('stored', models.BooleanField(default=False)),
                ('freezer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freeze_groups', to='profiles.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Strain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wja', models.IntegerField(unique=True)),
                ('description', models.CharField(max_length=255, null=True)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('phenotype', models.CharField(max_length=255, null=True)),
                ('formatted_wja', models.CharField(editable=False, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cap_color', models.CharField(default='N/A', max_length=50)),
                ('date_created', models.DateField(auto_now_add=True)),
                ('date_thawed', models.DateField(null=True)),
                ('thawed', models.BooleanField(default=False)),
                ('thaw_requester', models.CharField(max_length=50, null=True)),
                ('box', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tube_set', to='ArribereNemaStocks.box')),
                ('freeze_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tube_set', to='ArribereNemaStocks.freezegroup')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tube_set', to='ArribereNemaStocks.strain')),
            ],
        ),
        migrations.CreateModel(
            name='ThawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('request_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('completed', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thaw_requests', to='profiles.userprofile')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thaw_requests', to='ArribereNemaStocks.strain')),
                ('thawed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thawed_tubes', to='profiles.userprofile')),
                ('tube', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArribereNemaStocks.tube')),
            ],
        ),
        migrations.CreateModel(
            name='FreezeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('request_comments', models.CharField(blank=True, max_length=255, null=True)),
                ('date_advanced', models.DateField(null=True)),
                ('advanced', models.BooleanField(default=False)),
                ('number_of_tubes', models.IntegerField(default=1)),
                ('cap_color', models.CharField(blank=True, max_length=50, null=True)),
                ('freeze_group', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArribereNemaStocks.freezegroup')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to='profiles.userprofile')),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to='ArribereNemaStocks.strain')),
            ],
        ),
        migrations.AddField(
            model_name='freezegroup',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArribereNemaStocks.strain'),
        ),
        migrations.AddField(
            model_name='freezegroup',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tested_freeze_groups', to='profiles.userprofile'),
        ),
    ]
