# Generated by Django 4.2.7 on 2023-11-22 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tube',
            name='strain',
            field=models.ForeignKey(choices=[], on_delete=django.db.models.deletion.CASCADE, related_name='tube_set', to='ArribereNemaStocks.strain'),
        ),
    ]
