# Generated by Django 4.2.9 on 2024-01-24 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstrain',
            name='additional_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='additional_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
