# Generated by Django 4.2.7 on 2023-11-21 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezegroup',
            name='test_check_date',
            field=models.DateTimeField(null=True),
        ),
    ]
