# Generated by Django 4.2.7 on 2024-01-22 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_other_associated_initials'),
        ('ArribereNemaStocks', '0002_alter_box_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezegroup',
            name='tester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tested_freeze_groups', to='profiles.userprofile'),
        ),
    ]
