# Generated by Django 4.2.9 on 2024-01-26 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0002_historicalstrain_additional_comments_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='box',
            options={'verbose_name_plural': 'Boxes'},
        ),
        migrations.AlterModelOptions(
            name='historicalbox',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical box', 'verbose_name_plural': 'historical Boxes'},
        ),
        migrations.AddField(
            model_name='historicaltube',
            name='set_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AddField(
            model_name='tube',
            name='set_number',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='historicaltube',
            name='cap_color',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='tube',
            name='cap_color',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='freezegroup',
            unique_together={('date_created', 'strain')},
        ),
        migrations.AlterUniqueTogether(
            name='tube',
            unique_together={('strain', 'freeze_group', 'set_number')},
        ),
    ]
