# Generated by Django 4.2.7 on 2023-11-22 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0002_alter_tube_strain'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='phenotype',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='tube',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tube_set', to='ArribereNemaStocks.strain'),
        ),
    ]
