# Generated by Django 4.2.7 on 2023-11-22 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArribereNemaStocks', '0003_strain_phenotype_alter_tube_strain'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('is_urgent', models.BooleanField(default=False)),
                ('request_comments', models.CharField(max_length=255, null=True)),
                ('date_completed', models.DateField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thaw_requests', to=settings.AUTH_USER_MODEL)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thaw_requests', to='ArribereNemaStocks.strain')),
                ('thawed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thawed_tubes', to=settings.AUTH_USER_MODEL)),
                ('tube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArribereNemaStocks.tube')),
            ],
        ),
        migrations.CreateModel(
            name='FreezeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateField(auto_now_add=True)),
                ('request_comments', models.CharField(max_length=255, null=True)),
                ('date_completed', models.DateField(null=True)),
                ('completed', models.BooleanField(default=False)),
                ('freeze_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to='ArribereNemaStocks.freezegroup')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to=settings.AUTH_USER_MODEL)),
                ('strain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to='ArribereNemaStocks.strain')),
                ('tube', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to='ArribereNemaStocks.tube')),
            ],
        ),
    ]
