# Generated by Django 4.2.9 on 2024-01-26 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0003_alter_box_options_alter_historicalbox_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='freezegroup',
            unique_together={('strain', 'date_created')},
        ),
    ]
