# Generated by Django 4.2.9 on 2024-01-26 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0004_alter_freezegroup_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='freezegroup',
            unique_together={('strain', 'date_stored')},
        ),
    ]
