# Generated by Django 4.2.7 on 2023-11-22 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0004_thawrequest_freezerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thawrequest',
            name='date_completed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='thawrequest',
            name='tube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArribereNemaStocks.tube'),
        ),
    ]
