# Generated by Django 4.2.7 on 2023-11-22 21:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ArribereNemaStocks', '0005_alter_thawrequest_date_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thawrequest',
            name='thawed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thawed_tubes', to=settings.AUTH_USER_MODEL),
        ),
    ]
