# Generated by Django 4.2.9 on 2024-01-26 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0005_alter_freezegroup_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tube',
            unique_together={('strain', 'freeze_group', 'box', 'set_number')},
        ),
    ]
