# Generated by Django 4.2.9 on 2024-01-26 03:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0006_alter_tube_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstrain',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='strain',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
