# Generated by Django 4.2.9 on 2024-01-27 01:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0007_alter_historicalstrain_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezerequest',
            name='advanced',
        ),
        migrations.RemoveField(
            model_name='historicalfreezerequest',
            name='advanced',
        ),
        migrations.AddField(
            model_name='freezegroup',
            name='freeze_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArribereNemaStocks.freezerequest'),
        ),
        migrations.AddField(
            model_name='freezerequest',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('A', 'Advanced'), ('C', 'Completed'), ('F', 'Failed'), ('X', 'Cancelled')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='historicalfreezegroup',
            name='freeze_request',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ArribereNemaStocks.freezerequest'),
        ),
        migrations.AddField(
            model_name='historicalfreezerequest',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('A', 'Advanced'), ('C', 'Completed'), ('F', 'Failed'), ('X', 'Cancelled')], default='R', max_length=1),
        ),
        migrations.AlterField(
            model_name='freezegroup',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='freezerequest',
            name='cap_color',
            field=models.CharField(blank=True, choices=[('', '---------'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('lavender', 'Lavender'), ('purple', 'Purple'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('grey', 'Grey'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfreezegroup',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='historicalfreezerequest',
            name='cap_color',
            field=models.CharField(blank=True, choices=[('', '---------'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('lavender', 'Lavender'), ('purple', 'Purple'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('grey', 'Grey'), ('unknown', 'Unknown')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='historicaltube',
            name='cap_color',
            field=models.CharField(choices=[('', '---------'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('lavender', 'Lavender'), ('purple', 'Purple'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('grey', 'Grey'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaltube',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tube',
            name='cap_color',
            field=models.CharField(choices=[('', '---------'), ('pink', 'Pink'), ('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('lavender', 'Lavender'), ('purple', 'Purple'), ('white', 'White'), ('brown', 'Brown'), ('gray', 'Gray'), ('grey', 'Grey'), ('unknown', 'Unknown')], default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='tube',
            name='date_created',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
