# Generated by Django 4.2.9 on 2024-01-27 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0008_remove_freezerequest_advanced_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalthawrequest',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('O', 'Ongoing'), ('C', 'Completed'), ('X', 'Cancelled')], default='R', max_length=1),
        ),
        migrations.AddField(
            model_name='thawrequest',
            name='status',
            field=models.CharField(choices=[('R', 'Requested'), ('O', 'Ongoing'), ('C', 'Completed'), ('X', 'Cancelled')], default='R', max_length=1),
        ),
    ]
