# Generated by Django 4.2.7 on 2023-11-27 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0008_alter_thawrequest_thawed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='strain',
            name='formatted_wja',
            field=models.CharField(default='WJAXXXX', editable=False, max_length=8),
            preserve_default=False,
        ),
    ]
