# Generated by Django 4.2.9 on 2024-01-28 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('ArribereNemaStocks', '0009_historicalthawrequest_status_thawrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltube',
            name='thaw_requester',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='thawrequest',
            name='thawed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='czar_thawed_tubes', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='tube',
            name='thaw_requester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thawed_tubes', to='profiles.userprofile'),
        ),
    ]
