# Generated by Django 4.2.7 on 2023-12-22 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0009_strain_formatted_wja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezerequest',
            name='freeze_group',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='ArribereNemaStocks.freezegroup'),
        ),
    ]
