# Generated by Django 4.2.9 on 2024-01-29 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0010_alter_historicaltube_thaw_requester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaltube',
            name='date_thawed',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tube',
            name='date_thawed',
            field=models.DateField(blank=True, null=True),
        ),
    ]
