# Generated by Django 4.2.7 on 2023-12-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0010_alter_freezerequest_freeze_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='freezerequest',
            name='tube',
        ),
        migrations.AddField(
            model_name='freezerequest',
            name='number_of_tubes',
            field=models.IntegerField(default=1),
        ),
    ]
