# Generated by Django 4.2.7 on 2023-12-22 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0011_remove_freezerequest_tube_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezerequest',
            name='request_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
