# Generated by Django 4.2.9 on 2024-09-20 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0012_alter_freezerequest_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezerequest',
            name='box1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box1_freeze_requests', to='ArribereNemaStocks.box'),
        ),
        migrations.AddField(
            model_name='freezerequest',
            name='box2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='box2_freeze_requests', to='ArribereNemaStocks.box'),
        ),
        migrations.AddField(
            model_name='freezerequest',
            name='tubes_for_box1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='freezerequest',
            name='tubes_for_box2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfreezerequest',
            name='box1',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ArribereNemaStocks.box'),
        ),
        migrations.AddField(
            model_name='historicalfreezerequest',
            name='box2',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='ArribereNemaStocks.box'),
        ),
        migrations.AddField(
            model_name='historicalfreezerequest',
            name='tubes_for_box1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalfreezerequest',
            name='tubes_for_box2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
