# Generated by Django 4.2.7 on 2023-12-22 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_userprofile_active_status'),
        ('ArribereNemaStocks', '0012_alter_freezerequest_request_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezerequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_requests', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='thawrequest',
            name='requester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thaw_requests', to='profiles.userprofile'),
        ),
        migrations.AlterField(
            model_name='thawrequest',
            name='thawed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thawed_tubes', to='profiles.userprofile'),
        ),
    ]
