# Generated by Django 4.2.9 on 2024-09-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0014_alter_freezerequest_tubes_for_box1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezerequest',
            name='tubes_for_box1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezerequest',
            name='tubes_for_box2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfreezerequest',
            name='tubes_for_box1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalfreezerequest',
            name='tubes_for_box2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
