# Generated by Django 4.2.7 on 2024-01-09 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0015_alter_freezerequest_cap_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thawrequest',
            name='request_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
