# Generated by Django 4.2.9 on 2024-09-20 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0015_alter_freezerequest_tubes_for_box1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezerequest',
            name='tester_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='historicalfreezerequest',
            name='tester_comments',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
