# Generated by Django 4.2.9 on 2024-09-21 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0016_freezerequest_tester_comments_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='freezegroup',
            unique_together=set(),
        ),
    ]
