# Generated by Django 4.2.7 on 2024-01-10 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0017_historicaltube_historicalthawrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstrain',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstrain',
            name='phenotype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='phenotype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
