# Generated by Django 4.2.9 on 2024-09-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_remove_userprofile_all_associated_initials_and_more'),
        ('ArribereNemaStocks', '0018_freezerequest_tester_historicalfreezerequest_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='freezerequest',
            name='freezer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='freeze_requests_again', to='profiles.userprofile'),
        ),
        migrations.AddField(
            model_name='historicalfreezerequest',
            name='freezer',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='profiles.userprofile'),
        ),
    ]
