# Generated by Django 4.2.9 on 2024-09-24 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0019_freezerequest_freezer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstrain',
            name='genotype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='genotype',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
