# Generated by Django 4.2.9 on 2024-09-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0022_openstrainediting_historicalopenstrainediting'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalopenstrainediting',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openstrainediting',
            name='is_open',
            field=models.BooleanField(default=False),
        ),
    ]
