# Generated by Django 4.2.9 on 2024-09-27 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0023_historicalopenstrainediting_is_open_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalopenstrainediting',
            old_name='is_open',
            new_name='edit_any',
        ),
        migrations.RenameField(
            model_name='openstrainediting',
            old_name='is_open',
            new_name='edit_any',
        ),
        migrations.AddField(
            model_name='historicalopenstrainediting',
            name='edit_own',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='openstrainediting',
            name='edit_own',
            field=models.BooleanField(default=False),
        ),
    ]
