# Generated by Django 4.2.9 on 2024-09-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0024_rename_is_open_historicalopenstrainediting_edit_any_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalopenstrainediting',
            name='edit_any',
        ),
        migrations.RemoveField(
            model_name='historicalopenstrainediting',
            name='edit_own',
        ),
        migrations.RemoveField(
            model_name='openstrainediting',
            name='edit_any',
        ),
        migrations.RemoveField(
            model_name='openstrainediting',
            name='edit_own',
        ),
    ]
