# Generated by Django 4.2.9 on 2024-09-27 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0025_remove_historicalopenstrainediting_edit_any_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalopenstrainediting',
            name='edit_ability',
            field=models.CharField(choices=[('A', 'Edit Any Strains'), ('O', 'Edit Own Strains'), ('N', 'No Editing Permissions')], default='N', max_length=1),
        ),
        migrations.AddField(
            model_name='openstrainediting',
            name='edit_ability',
            field=models.CharField(choices=[('A', 'Edit Any Strains'), ('O', 'Edit Own Strains'), ('N', 'No Editing Permissions')], default='N', max_length=1),
        ),
    ]
