# Generated by Django 4.2.9 on 2024-09-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0026_historicalopenstrainediting_edit_ability_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalstrain',
            name='additional_description',
        ),
        migrations.RemoveField(
            model_name='strain',
            name='additional_description',
        ),
        migrations.AddField(
            model_name='historicalstrain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalstrain',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='additional_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
