# Generated by Django 4.2.9 on 2024-09-30 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0027_remove_historicalstrain_additional_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstrain',
            name='phenotype',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='strain',
            name='phenotype',
            field=models.TextField(blank=True, null=True),
        ),
    ]
