# Generated by Django 4.2.9 on 2024-10-03 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0028_alter_historicalstrain_phenotype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalstrain',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='strain',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
