# Generated by Django 4.2.9 on 2024-10-16 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0029_historicalstrain_source_strain_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezegroup',
            name='strain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freeze_groups', to='ArribereNemaStocks.strain'),
        ),
    ]
