# Generated by Django 4.2.9 on 2024-10-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArribereNemaStocks', '0030_alter_freezegroup_strain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezegroup',
            name='freeze_request',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArribereNemaStocks.freezerequest'),
        ),
    ]
